apiVersion: v1
kind: Service
metadata:
  name: fdb-server-service
  labels:
    name: fdb-server-service
spec:
  type: NodePort
  selector:
    app: fdb-server
  ports:
    - protocol: TCP
      port: 31111
      targetPort: 31111
      nodePort: 31111